### ISSUE TITLE
Add more in-depth end-to-end tests

### ISSUE THREAD

**Issue by arschles** [Azure/helm-charts#1]
_From @arschles on October 19, 2017 20:16_

Since these charts are to be installed on a Kubernetes cluster with service-catalog installed, we should have end-to-end tests that ensure that a `helm install` and `helm delete` on each chart works as appropriate.

**Comment by arschles** [comment]
@carolynvs, @krancour, @jeremyrickard, @bucksteamy and I discussed some ideas offline:

- To start, we could refine our documentation to be really specific about the requirements (i.e. specifying an exact Minikube version, even if it's not the latest) for running these charts
- We know we need better testing but should probably start small. Ideas:
    - Create a PR template that indicates to folks that they need to test their charts at least on Minikube, and then tell us what other systems they tested on (if any)
    - Provide a script for folks to run tests easily
- Standing up a full CI system for these charts would be complex and would likely cause our PR builds to take _super long_. A few ideas to mitigate:
    - Only run CI on the chart(s) that were changed
    - Define a test matrix. For example: `{minikube, on-cluster}, {minikube, azure}, {AKS, on-cluster}, {AKS, azure}`
    - We should add 'hold for approval' to our CI system so that we're not running the suite on every push to a PR-ed branch. Instead, let's let maintainers run the suite when the PR is in a good state

Overall, we decided that we shouldn't go do the whole automated CI system right now. Instead, we think the best place to start is in docs & the local script. I vote for a binary instead of a script 😉

**Comment by carolynvs** [comment]
I agree that we should start with making it easier to test a single chart, instead of biting off the CI part. It will help people with their patch before they even submit a PR.
