### ISSUE TITLE
Helm chart for MongoDB

### ISSUE THREAD

**Issue by spacecat** [Azure/helm-charts#123]
https://github.com/kubernetes/charts/tree/master/stable/mongodb
https://github.com/Azure/meta-azure-service-broker/blob/master/docs/azure-cosmos-db.md

**Comment by spacecat** [comment]
https://github.com/kubernetes/charts/tree/master/stable/mongodb

**Comment by jeremyrickard** [comment]
Hey there @spacecat 

Could you provide a little more detail on what you're asking for here? Just a chart that provisions CosmosDB (with the MongoDB API)?

**Comment by spacecat** [comment]
Good question.
Was  clear to me yesterday but today it's not. =D

I think what I would like to see is a exactly what you re describing.

Eventually I would like to see a chart for Squidex (Headless CMS with a MongoDB)

But just a mongo db chart for now might be a good first step. 

Hope this makes more sense now. =D

**Comment by jeremyrickard** [comment]
Is there chart for Squidex upstream? We aren't _generally_ trying to expand our current set of charts, however, we don't really have a good CosmosDB (MongoDB) example. 

If you're looking for a simple example of how you might do that, we do have an example of using OSBA to provision MongoDB API for CosmosDB here: https://github.com/Azure/open-service-broker-azure/tree/master/contrib/k8s/examples/cosmosdb

That will show you an example instance and binding for the Mongo DB API on CosmosDB.

**Comment by krancour** [comment]
@spacecat, adding to what @jeremyrickard has said, this repo isn't meant to host Hem charts that effect installation of services like Mongo. Rather, it's meant to host Helm charts that effect installation of software that _uses_ services like Mongo. And more specifically, it aims is to provision those services from Azure via Kubernetes Service Catalog and the Open Service Broker for Azure.

i.e. This repo is meant for demo-ware where we say, "I'm Squidex (for example) and I need a Mongo. Watch me magically get that Mongo from Azure."

**Comment by krancour** [comment]
To that end, perhaps what you really mean to suggest is the addition of a Squidex chart?

**Comment by spacecat** [comment]
I see your point and thanks for clarifying what this repo is for.

And yes , that is what I ultimately would like to see, a Squidex chart. Or rather a one click install inside the Kubeapps UI. When installing the chart kubernetes spins up the front end container/pods and other objects and at the same time a cosmos db mongo instance is provisioned in Azure. Makes sense?

OSBA is also something I'm trying to wrap my head around .

**Comment by krancour** [comment]
@spacecat yes. What you're suggesting makes sense.

I should add that we're resistant to this repo becoming a massive collection of things forked from kubernetes/charts with the OSBA bits added in. Add this point, we're prioritizing chart value based on whether it demos some Azure service provisioned via OSBA _that we aren't already demoing_. i.e. We don't need more MySQL examples. We have them coming out of our ears.

We don't currently have any examples that utilize Cosmos. So the chart you're proposing adding fits very nicely with our current priorities.
