### ISSUE TITLE
Implement Magento

### ISSUE THREAD

**Issue by arschles** [Azure/helm-charts#13]
_From @arschles on September 5, 2017 22:25_

There is a Magento chart [here](https://github.com/kubernetes/charts/tree/master/stable/magento) which relies on an in-cluster MariaDB database (see [here](https://github.com/kubernetes/charts/blob/master/stable/magento/requirements.yaml)). 

A new chart should be created here that satisfies the MariaDB service dependency with Azure SQL for MySQL.

**Comment by sabbour** [comment]
I'm working on this. Blocked by https://github.com/Azure/open-service-broker-azure/issues/197 at the moment which seems fairly similar to https://github.com/Azure/open-service-broker-azure/issues/16.

**Comment by sabbour** [comment]
Created a PR for this https://github.com/Azure/helm-charts/pull/109
