### ISSUE TITLE
wordpress chart version 0.10.1 did not push to blob storage after merge

### ISSUE THREAD

**Issue by jldeen** [Azure/helm-charts#133]
[Issue #593](https://github.com/Azure/open-service-broker-azure/issues/593) reported on the Open Service Broker Repo stated 404 error when trying to use azure/wordpress repo (after adding repo and running `helm repo update`) I can +1 same error. Running same command (`helm install azure/wordpress --name osba-quickstart --namespace osba-quickstart`)with --version flag and 0.10.0 works.

**Comment by krancour** [comment]
Thanks for reporting this. This is quite odd. I'm browsing the Azure Storage account that hosts these charts and am finding that the file _does_ exist, but is misnamed. It is `wordpress-010.1.tgz` when it should be (according to our publishing process and the index) `wordpress-0.10.1.tgz`.

Clearly, there's a bug in our publishing process. Will look into it.
