### ISSUE TITLE
Implement RocketChat

### ISSUE THREAD

**Issue by arschles** [Azure/helm-charts#5]
_From @arschles on September 5, 2017 22:33_

There is a RocketChat chart [here](https://github.com/kubernetes/charts/tree/master/stable/rocketchat) which relies on an in-cluster MongoDB database (see [here](https://github.com/kubernetes/charts/blob/master/stable/rocketchat/requirements.yaml)). 

A new chart should be created here that satisfies the MongoDB service dependency with Azure CosmosDB.

**Comment by hairmare** [comment]
The "official" chart  supports skipping the install of an in-cluster MongoDB database since https://github.com/helm/charts/pull/10875.

During startup there are still some errors. At a glance it looks like CosmosDB is missing some features needed by Rocketchat.

```
Error creating index: message -> { msg: 'text' } { MongoError: 'text' is not supported...
...
Exception while invoking method 'UserPresence:online' { MongoError: The dollar ($) prefixed field 'connections.$.status' in 'connections.$.status' is not valid for storage.
```
