### ISSUE TITLE
MySQL / PostgreSQL servicePlan standard800 is too big / expensive to be a default

### ISSUE THREAD

**Issue by krancour** [Azure/helm-charts#83]
Several charts are using this _expensive_ DB as a default. This doesn't seem optimal.

**Comment by ritazh** [comment]
@krancour agreed that this should be configurable. just a note that this plan was used as it gave us the fastest mysql deployment during tests we did in the past.

**Comment by krancour** [comment]
> just a note that this plan was used as it gave us the fastest mysql deployment during tests we did in the past.

Agreed-- you and I both may want speed, but an almost $600/month database isn't a good default for the growing number of users who will try these charts.

**Comment by ritazh** [comment]
Totally agreed that should NOT be the default

**Comment by krancour** [comment]
There's only one chart remaining that is affected by this. Closing this and making an issue for that chart.
