### ISSUE TITLE
wordpress-0.6.12.tgz from helm repo out of sync with git

### ISSUE THREAD

**Issue by AceHack** [Azure/helm-charts#99]
tls parameter is not working with helm install using repo

When I git clone and run helm install using local copy tls settings work fine

**Comment by AceHack** [comment]
How do I know what's in a release?  Does it get tagged here on github?

**Comment by jeremyrickard** [comment]
Hey @AceHack, the chart was updated to 0.7.0 a few weeks ago and the release should be there in the repo:
 
>$ helm inspect azure/wordpress | yq .version
"0.7.0"


Are you still getting wordpress-0.6.12.tgz from the Azure repo when you helm install? If so, could you try installing with --version 0.7.0
